[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "physicell_studio"
authors = [{name = "Randy Heiland", email = "randy.heiland@gmail.com"}]
dynamic = ["version", "description"]
